### ISSUE TITLE
ros_setup_scripts_Ubuntu18.04_desktopでのエラー

### ISSUE THREAD

**Issue by ba2vwbus13** [ryuichiueda/pimouse_slam#1]
ros_setup_scripts_Ubuntu18.04_desktopをつかってPCにROSをインストール後
13.3.2章の以下のコマンドを打つとエラーになりました。
原因がわかれば教えていただけますでしょうか。

$ rosrun rqt_tf_tree rqt_tf_tree 
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/rqt_tf_tree/rqt_tf_tree", line 5, in <module>
    from rqt_gui.main import Main
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 38, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'

**Comment by ryuichiueda** [comment]
こちらもおそくなってすみません。最終行に

ModuleNotFoundError: No module named 'rospkg'

とあるので、rospkgというモジュールがない（あるいはパスが通っていない）ということになります。おそらく

```
sudo apt-get install python-rospkg
```

でインストールできますが、もしダメでしたらまたおしらせください。

参考: http://wiki.ros.org/rospkg#Installing_rospkg
